name: "Sonar Scan for Go"
description: "Run sonar-scanner for Go coverage"
inputs:
  go_mod_dir:
    required: true
  sonar-project-key:
    required: true
  sonar-token:
    required: true
  sonar-organization:
    required: true
  sonar-host-url:
    required: true
runs:
  using: "composite"
  steps:
    - name: Install sonar-scanner
      shell: bash
      run: |
        npm -g install sonar-scanner@3.1.0

    - name: Validate sonar-project.properties
      working-directory: ${{ inputs.go_mod_dir }}
      shell: bash
      run: |
        if [ ! -f "sonar-project.properties" ]; then
          echo "::error::sonar-project.properties not found in $PWD"
          exit 1
        fi

    - name: Run sonar-scanner
      working-directory: ${{ inputs.go_mod_dir }}
      env:
        SONAR_TOKEN: ${{ inputs.sonar-token }}
      shell: bash
      run: |
        sonar-scanner \
          -Dproject.settings=sonar-project.properties \
          -Dsonar.projectKey=${{ inputs.sonar-project-key }} \
          -Dsonar.organization=${{ inputs.sonar-organization }} \
          -Dsonar.host.url=${{ inputs.sonar-host-url }} \
          -Dsonar.go.coverage.reportPaths=coverage.out
