name: Check Open PR
description: Detect if there is an open PR for the current branch

outputs:
  hasOpenPr:
    description: "true/false if open PR exists for current branch"
    value: ${{ steps.find.outputs.hasOpenPr }}

runs:
  using: "composite"
  steps:
    - id: find
      uses: actions/github-script@v7
      with:
        github-token: ${{ github.token }}
        script: |
          const branch = process.env.GITHUB_HEAD_REF || process.env.GITHUB_REF_NAME;
          const owner  = context.repo.owner;
          const { data: prs } = await github.rest.pulls.list({
            owner,
            repo: context.repo.repo,
            state: 'open',
            head: `${owner}:${branch}`,
            per_page: 1
          });
          core.notice(`Open PR on branch "${branch}": ${prs.length > 0}`);
          core.setOutput('hasOpenPr', prs.length > 0 ? 'true' : 'false');
