name: Build Go Service

on:
  workflow_call:
    inputs:
      sonar-project-key:
        required: true
        type: string
    secrets:
      sonar-token:
        required: true

concurrency:
  group: ci-${{ github.event_name }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  pr-check:
    runs-on: ubuntu-latest
    outputs:
      hasOpenPr: ${{ steps.find.outputs.hasOpenPr }}
    steps:
      - id: find
        uses: actions/github-script@v7
        with:
          script: |
            const branch = process.env.GITHUB_HEAD_REF || process.env.GITHUB_REF_NAME;
            const owner  = context.repo.owner;
            const { data: prs } = await github.rest.pulls.list({
              owner,
              repo: context.repo.repo,
              state: 'open',
              head: `${owner}:${branch}`,
              per_page: 1
            });
            core.notice(`Open PR on branch "${branch}": ${prs.length > 0}`);
            core.setOutput('hasOpenPr', prs.length > 0 ? 'true' : 'false');

  fast-exit-on-push-when-pr-exists:
    needs: pr-check
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && needs.pr-check.outputs.hasOpenPr == 'true' }}
    steps:
      - run: echo "PR exists for this branch -> work is delegated to pull_request workflow. Exiting."

  build-with-sonar:
    needs: pr-check
    if: ${{ github.event_name == 'pull_request' || needs.pr-check.outputs.hasOpenPr == 'false' }}
    uses: taurmorchant/workflows-test/.github/workflows/go-build-with-sonar.yaml@v1.0.5
    with:
      actor: ${{ github.actor }}
      sonar-project-key: ${{ inputs.sonar-project-key }}
    secrets:
      sonar-token: ${{ secrets.sonar-token }}
