# ------------------------------------------------------------------------------
# Workflow: Generic build
#
# Purpose:
#   Reusable workflow to build/test Java libs and run SonarCloud analysis
#
# Trigger:
#   - workflow_call with inputs:
#       sonar-project-key (optional) : SonarCloud project key
#       actor             (required) : GitHub actor triggering the run
#     and secret:
#       sonar-token (required) : SonarCloud token
#
# Logic:
#   1. check-pr:
#        - Detects if an open PR exists for the branch.
#        - If push to a branch with an open PR → skip and delegate to PR workflow.
#   2. go-build:
#        - Runs if not delegated.
#        - Builds/tests Java module with Maven and runs SonarCloud analysis.
#   3. docker-build:
#        - Runs after go-build if not delegated.
#        - Builds Docker image.
#
# Permissions: contents: read, pull-requests: write, packages: write
# Concurrency: one run per branch/event, older runs canceled
# ------------------------------------------------------------------------------

name: Generic build

on:
  workflow_call:
    inputs:
      sonar-project-key:
        description: 'Sonar project key for analysis. It must be specified explicitly, as the qubership-core-infra repository may have its own sonar-project-key. '
        required: false
        type: string
      actor:
        description: 'GitHub actor (user or bot) that triggered the workflow'
        required: true
        type: string
    secrets:
      sonar-token:
        required: true

permissions:
  contents: read
  pull-requests: write
  packages: write

concurrency:
  group: ci-${{ github.event_name }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  check-pr:
    name: Check is PR exists
    runs-on: ubuntu-latest
    outputs:
      hasOpenPr: ${{ steps.pr.outputs.hasOpenPr }}
    steps:
      - name: Check for open PR
        id: pr
        uses: taurmorchant/workflows-test/.github/actions/check-open-pr@main

      - name: Explain routing decision
        if: ${{ github.event_name == 'push' && steps.pr.outputs.hasOpenPr == 'true' }}
        run: |
          {
            echo "### Router decision"
            echo ""
            echo "- Event: \`${{ github.event_name }}\`"
            echo "- Branch: \`${{ github.head_ref || github.ref_name }}\`"
            echo "- Open PR detected: **yes**"
            echo ""
            echo "Work is delegated to the PR workflow. Skip next steps."
          } >> "$GITHUB_STEP_SUMMARY"

  go-build:
    name: Build and test Java module
    needs: [ check-pr ]
    if: ${{ !(github.event_name == 'push' && needs.check-pr.outputs.hasOpenPr == 'true') }}
    uses: taurmorchant/workflows-test/.github/workflows/maven-build-with-sonar.yaml@main
    with:
      event-name: ${{ github.event_name }}
      actor: ${{ inputs.actor }}
      sonar-project-key: ${{ inputs.sonar-project-key }}
      upload-artifact: true
    secrets:
      sonar-token: ${{ secrets.sonar-token }}