# Build Go Service Workflow
#
# Purpose:
#   A reusable workflow for building Go services with SonarCloud code analysis
#   and Docker image publishing. Can be invoked from other workflows (workflow_call).
#
# Inputs:
#   sonar-project-key – SonarCloud project key
#   go-module-dir     – Directory containing go.mod (optional, if not provided, go.mod will be searched in the repo).
#   actor             – GitHub actor (user or bot) that triggered the workflow (required).
#
# Secrets:
#   sonar-token – Token for accessing SonarCloud (required).
#
# Workflow logic:
#   1. pr-check:
#      Detects if there is an open Pull Request for the current branch.
#   2. fast-exit-on-push-when-pr-exists:
#      If the event is "push" and an open PR exists – exits early,
#      delegating the work to the pull_request workflow.
#   3. build-with-sonar:
#      Runs Go build and SonarCloud analysis:
#        • on pull_request events, or
#        • on push events if no open PR exists.
#      Uses the shared workflow go-build-with-sonar from core-infra.
#   4. docker-build:
#      After a successful build, runs Docker image build
#      using the shared docker-build workflow from core-infra.

name: Build Go Service

on:
  workflow_call:
    inputs:
      sonar-project-key:
        description: 'Sonar project key for analysis. It must be specified explicitly, as the qubership-core-infra repository may have its own sonar-project-key. '
        required: false
        type: string
      go-module-dir:
        description: 'Optional directory containing go.mod file. If not specified, will search for go.mod files in the repository.'
        required: false
        type: string
      actor:
        description: 'GitHub actor (user or bot) that triggered the workflow'
        required: true
        type: string
    secrets:
      sonar-token:
        required: true

concurrency:
  group: ci-${{ github.event_name }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  packages: write

jobs:
  check-open-pr:
    runs-on: ubuntu-latest
    outputs:
      hasOpenPr: ${{ steps.pr.outputs.hasOpenPr }}
    steps:
      - id: pr
        uses: taurmorchant/workflows-test/.github/actions/check-open-pr@main

  fast-exit-on-push-when-pr-exists:
    needs: [ check-open-pr ]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && needs.check-open-pr.outputs.hasOpenPr == 'true' }}
    steps:
      - run: echo "PR exists for this branch -> work is delegated to pull_request workflow. Exiting."

  build-with-sonar:
    needs: [ check-open-pr ]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' || needs.check-open-pr.outputs.hasOpenPr == 'false' }}
    steps:
      - name: Go build with Sonar
        uses: taurmorchant/workflows-test/.github/actions/go-build-with-sonar@main
        with:
          actor: ${{ github.actor }}
          go-module-dir: ${{ inputs.go-module-dir }}
          sonar-project-key: ${{ inputs.sonar-project-key }}
          sonar-token: ${{ secrets.sonar-token }}
          sonar-organization: ${{ vars.SONAR_ORGANIZATION }}
          sonar-host-url: ${{ vars.SONAR_HOST_URL }}

  docker-build:
    needs: [ build-with-sonar ]
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODO Imitate docker build"
