name: Deploy to Maven Repository + Sonar

on:
  workflow_call:
    inputs:
      event-name:
        required: true
        type: string
      actor:
        required: true
        type: string
      java-version:
        required: false
        type: string
        default: "21"
      sonar-project-key:
        required: false
        type: string
    secrets:
      maven-token:
        required: true
      sonar-token:
        required: false

jobs:
  prepare-variables:
    runs-on: ubuntu-latest
    outputs:
      maven-goal: ${{ steps.prepare.outputs.maven-goal }}
      run-sonar: ${{ steps.prepare.outputs.run-sonar }}
    steps:
      - name: TMP event-name
        run: echo ${{ inputs.event-name }}
      - name: TMP actor
        run: echo ${{ inputs.actor }}
      - name: Checkout workflow repository
        uses: actions/checkout@v4
        with:
          repository: TaurMorchant/workflows-test
          ref: main
          path: workflow-repo
      - name: Prepare variables
        id: prepare
        run: |
          ACTOR="${{ inputs.actor }}"
          EVENT_NAME="${{ inputs.event-name }}"
          
          # Check if Sonar is configured
          if [ -z "${{ inputs.sonar-project-key }}" ] || [ -z "${{ secrets.sonar-token }}" ]; then
            echo "run-sonar=false" >> $GITHUB_OUTPUT
          else
            if yq e '.restricted-actors[]' workflow-repo/.github/config/maven-build-config.yaml | grep -q "^$ACTOR$"; then
              IS_RESTRICTED_ACTOR=true
            else
              IS_RESTRICTED_ACTOR=false
            fi

            if [ "$EVENT_NAME" = "pull_request" ]; then
              echo "maven-goal=verify" >> $GITHUB_OUTPUT
              if [ "$IS_RESTRICTED_ACTOR" = true ]; then
                echo "run-sonar=false" >> $GITHUB_OUTPUT
              else
                echo "run-sonar=true" >> $GITHUB_OUTPUT
              fi
            elif [ "$EVENT_NAME" = "push" ]; then
              if [ "$IS_RESTRICTED_ACTOR" = true ]; then
                echo "maven-goal=verify" >> $GITHUB_OUTPUT
                echo "run-sonar=false" >> $GITHUB_OUTPUT
              else
                echo "maven-goal=deploy" >> $GITHUB_OUTPUT
                echo "run-sonar=true" >> $GITHUB_OUTPUT
              fi
            else
              echo "::error::Unsupported event name: $EVENT_NAME. Only 'pull_request' and 'push' are supported."
              exit 1
            fi
          fi
      - name: Output maven goal
        run: echo ${{ steps.prepare.outputs.maven-goal }}
      - name: Output run sonar
        run: echo ${{ steps.prepare.outputs.run-sonar }}

  mvn-with-sonar:
    needs: prepare-variables
    if: needs.prepare-variables.outputs.run-sonar == 'true'
    uses: netcracker/qubership-workflow-hub/.github/workflows/maven-publish.yml@v1.0.1
    with:
      maven-command: >
        --batch-mode ${{ needs.prepare-variables.outputs.maven-goal }}
        -Dgpg.skip=true 
        org.sonarsource.scanner.maven:sonar-maven-plugin:${{ vars.SONAR_PLUGIN_VERSION }}:sonar 
        -Dsonar.projectKey=${{ inputs.sonar-project-key }}
        -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }} 
        -Dsonar.host.url=${{ vars.SONAR_HOST_URL }}
      server-id: github
      java-version: ${{ inputs.java-version }}
      ref: ${{ github.head_ref }}
    secrets:
      maven-token: ${{ secrets.maven-token }}
      sonar-token: ${{ secrets.sonar-token }}

  mvn-without-sonar:
    needs: prepare-variables
    if: needs.prepare-variables.outputs.run-sonar == 'false'
    uses: netcracker/qubership-workflow-hub/.github/workflows/maven-publish.yml@v1.0.1
    with:
      maven-command: >
        --batch-mode ${{ needs.prepare-variables.outputs.maven-goal }}
        -Dgpg.skip=true
      server-id: github
      java-version: ${{ inputs.java-version }}
      ref: ${{ github.head_ref }}
    secrets:
      maven-token: ${{ secrets.maven-token }}