name: Deploy to Maven Repository + Sonar

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: "21"
      sonar-project-key:
        required: true
        type: string
      event-name:
        required: true
        type: string
      actor:
        required: true
        type: string
    secrets:
      maven-token:
        required: true
      sonar-token:
        required: true

jobs:
  prepare-variables:
    runs-on: ubuntu-latest
    outputs:
      maven-goal: ${{ steps.prepare.outputs.maven-goal }}
      sonar-skip: ${{ steps.prepare.outputs.sonar-skip }}
    steps:
      - name: TMP event-name
        run: echo ${{ inputs.event-name }}
      - name: TMP actor
        run: echo ${{ inputs.actor }}
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Prepare variables
        id: prepare
        run: |
          ACTOR="${{ inputs.actor }}"
          EVENT_NAME="${{ inputs.event-name }}"
          
          if [ "$EVENT_NAME" = "pull_request" ]; then
            echo "maven-goal=verify" >> $GITHUB_OUTPUT
            if yq e '.restricted-actors[]' .github/config/maven-build-config.yaml | grep -q "^$ACTOR$"; then
              echo "sonar-skip=true" >> $GITHUB_OUTPUT
            else
              echo "sonar-skip=false" >> $GITHUB_OUTPUT
            fi
          elif [ "$EVENT_NAME" = "push" ]; then
            if yq e '.restricted-actors[]' .github/config/maven-build-config.yaml | grep -q "^$ACTOR$"; then
              echo "maven-goal=verify" >> $GITHUB_OUTPUT
              echo "sonar-skip=true" >> $GITHUB_OUTPUT
            else
              echo "maven-goal=deploy" >> $GITHUB_OUTPUT
              echo "sonar-skip=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "::error::Unsupported event name: $EVENT_NAME. Only 'pull_request' and 'push' are supported."
            exit 1
          fi
      - name: Output maven goal
        run: echo ${{ steps.prepare.outputs.maven-goal }}
      - name: Output sonar skip
        run: echo ${{ steps.prepare.outputs.sonar-skip }}

  mvn-with-sonar:
    needs: prepare-variables
    if: needs.prepare-variables.outputs.sonar-skip == 'false'
    uses: netcracker/qubership-workflow-hub/.github/workflows/maven-publish.yml@v1.0.1
    with:
      maven-command: >
        --batch-mode ${{ needs.prepare-variables.outputs.maven-goal }}
        -Dgpg.skip=true 
        org.sonarsource.scanner.maven:sonar-maven-plugin:${{ vars.SONAR_PLUGIN_VERSION }}:sonar 
        -Dsonar.projectKey=${{ inputs.sonar-project-key }}
        -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }} 
        -Dsonar.host.url=${{ vars.SONAR_HOST_URL }}
      server-id: github
      java-version: ${{ inputs.java-version }}
      ref: ${{ github.head_ref }}
    secrets:
      maven-token: ${{ secrets.maven-token }}
      sonar-token: ${{ secrets.sonar-token }}

  mvn-without-sonar:
    needs: prepare-variables
    if: needs.prepare-variables.outputs.sonar-skip == 'true'
    uses: netcracker/qubership-workflow-hub/.github/workflows/maven-publish.yml@v1.0.1
    with:
      maven-command: >
        --batch-mode ${{ needs.prepare-variables.outputs.maven-goal }}
        -Dgpg.skip=true
      server-id: github
      java-version: ${{ inputs.java-version }}
      ref: ${{ github.head_ref }}
    secrets:
      maven-token: ${{ secrets.maven-token }}