name: Deploy to Maven Repository + Sonar

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: "21"
      sonar-project-key:
        required: true
        type: string
      event-name:
        required: true
        type: string
      actor:
        required: true
        type: string
    secrets:
      maven-token:
        required: true
      sonar-token:
        required: true

jobs:
  prepare-variables:
    runs-on: ubuntu-latest
    outputs:
      maven-goal: ${{ steps.set-maven-goal.outputs.maven-goal }}
    steps:
      - name: TMP event-name
        run: echo ${{ inputs.event-name }}
      - name: TMP actor
        run: echo ${{ inputs.actor }}
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set maven goal based on actor
        id: set-maven-goal
        run: |
          ACTOR="${{ inputs.actor }}"
          if yq e '.restricted-actors[]' .github/config/maven-build-config.yaml | grep -q "^$ACTOR$"; then
            echo "maven-goal=verify" >> $GITHUB_OUTPUT
          else
            echo "maven-goal=deploy" >> $GITHUB_OUTPUT
          fi
      - name: Output maven goal
        run: echo ${{ steps.set-maven-goal.outputs.maven-goal }}
  mvn:
    needs: prepare-variables
    uses: netcracker/qubership-workflow-hub/.github/workflows/maven-publish.yml@v1.0.1
    with:
      maven-command: >
        --batch-mode ${{ needs.prepare-variables.outputs.maven-goal }}
        -Dgpg.skip=true 
        org.sonarsource.scanner.maven:sonar-maven-plugin:${{ vars.SONAR_PLUGIN_VERSION }}:sonar 
        -Dsonar.projectKey=${{ inputs.sonar-project-key }}
        -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }} 
        -Dsonar.host.url=${{ vars.SONAR_HOST_URL }}
      server-id: github
      java-version: ${{ inputs.java-version }}
      ref: ${{ github.head_ref }}
    secrets:
      maven-token: ${{ secrets.maven-token }}
      sonar-token: ${{ secrets.sonar-token }}